type: pipeline-template
version: 1

name: nodejs-kaniko-ci
displayName: NodeJS Kaniko CI
description: Build and push Docker image using Kaniko on Kubernetes

templateType: PIPELINE

pipeline:
  agent:
    kubernetes:
      cloud: terralogic-eks-agent-2
      namespace: cloudbees-builds
      inheritFrom: jenkins-kaniko-agent-2
      defaultContainer: jnlp

  environment:
    IMAGE_NAME: kamalakar2210/youtubeclone
    CI_IMAGE_TAG: "${env.BUILD_NUMBER}"

  stages:
    - stage: Install Dependencies
      steps:
        - sh 'npm install'

    - stage: Kaniko Build & Push
      steps:
        - container: kaniko
          sh: |
            /kaniko/executor \
              --context $WORKSPACE \
              --dockerfile Dockerfile \
              --destination ${IMAGE_NAME}:${CI_IMAGE_TAG}
